name: terraform-provider-confluent-internal
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  branches:
  - master
  - /^v\d+\.\d+\.x$/
